network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s3:
            dhcp4: no
            dhcp6: false
            addresses:
              - 10.100.0.4/24
              - 10.100.0.5/24
            nameservers:
              addresses:
                - 8.8.8.8
            routes:
              #- to: default
              - to: 0.0.0.0/0
                via: 10.100.0.3
                on-link: true
