#!/bin/bash

SuggestOptions()
{
	echo "1) See the network card model, channel speed, operating mode, physical connection, MAC address"
	echo "2) See IPv4 configuration"
	echo "3) Configure IPv4 interface"
	echo "0) Exit"
}

ChooseOption()
{
	PrintEmptyLine
	read -p "What do you want? " option
	echo $option
}

HandleChoice()
{
	option=$1 # Parameter.

	PrintEmptyLine
	case $option in

	1)
		for interface in `ip -brief address show | awk '{print $1;}'`;
		do
			nic=`	lshw -class network | grep "product"`
			speed=`	ethtool $interface 	| grep "Speed"	`
			duplex=`ethtool $interface 	| grep "Duplex"	`
			link=`	ethtool $interface 	| grep "Link"	`
			mac=`	lshw -class network | grep "serial"	`
			echo "<------------>"
			echo $nic
			echo $speed
			echo $duplex
			echo $link
			echo $mac
		done
		;;

	2)
		for interface in `ip -brief address show | awk '{print $1;}'`;
		do
			ipAndMask=`ip -detail address show dev $interface | grep "inet " | awk '{print $2;}'`
			gate=`ip -human route show dev $interface`
			dns=`cat /etc/resolv.conf`
			echo "<------------>"
			echo $interface
			echo $ipAndMask
			echo $gate
			echo $dns
		done
		;;

	3)
		SuggestConfigureOptions
		PrintEmptyLine
		Configure $(ChooseOption)
		;;

	0)
		exit
		;;

	*)
		printf "Unknown command. Please, choose again:\n"
		;;

	esac

	PrintEmptyLine; PrintEmptyLine
	SuggestOptions
	HandleChoice $(ChooseOption)
}

Configure()
{
	option=$1 # Get first parameter with option.

	#echo $option
	case $option in

	1)
		ip="10.100.0.2"
		mask="255.255.255.0"
		gate="10.100.0.1"
		dns="8.8.8.8"

		ip address add $ip/$mask dev $interface 		# Set ip address.
		ip route delete default dev $interface 			# Remove old route.
		ip route add default via $gate dev $interface	# Set new route.
		echo "nameserver ${dns}" | tee /etc/resolv.conf	# Set DNS record.
		;;

	2)
		# -v for logging; -r for removing.
		dhclient -v -r $interface # Free current IP reservation.
		dhclient -v $interface # Set new IP address.
		;;

	3)
		ip -detail address show dev $interface
		PrintEmptyLine
		ip -detail route show
		PrintEmptyLine
		cat /etc/resolv.conf
		;;

	0)
		PrintEmptyLine; PrintEmptyLine
		SuggestOptions
		HandleChoice $(ChooseOption)
		;;

	*)
		echo "Unknown command. What interface is active?"
	esac

	PrintEmptyLine; PrintEmptyLine
	SuggestConfigureOptions
	Configure $(ChooseOption)
}

SuggestConfigureOptions()
{
	interface=`lshw -class network | grep "name" | awk '{print $3;}'`

	printf 'Ok, %s is now active\n' $interface
	echo "1) Configure manually"
	echo "2) Configure automatically"
	echo "3) See info about interface"
	echo "0) <--Back"
}

PrintEmptyLine()
{
	echo
}

# ----------------------------------------------------------------------
echo "Hello, this is the lab1 script for configuring IP"
echo
echo "Here are several options:"

SuggestOptions
chosenOption=$(ChooseOption)
echo $chosenOption
HandleChoice $chosenOption
